in:
  type: file
  path_prefix: /home/ubuntu/dlog/messages
  parser:
    type: regex
    regex: '(?<time>.+) (?<host>DC-.+) sheep\[(?<port>\d+)\]: +(?<loglevel>\w+) \[(?<thread>\w+).*(?<threadNumber>\d*)\] (?<functionName>\w+)\((?<lineNumber>\d+)\) (?<errorMessage>.+)'
    columns:
    - {name: time, type: timestamp, format: '%b %d %H:%M:%S'}
    - {name: host, type: string}
    - {name: port, type: long}
    - {name: loglevel, type: string}
    - {name: thread, type: string}
    - {name: thread_number, type: long, regex_name: threadNumber}
    - {name: function_name, type: string, regex_name: functionName}
    - {name: line_number, type: long, regex_name: lineNumber}
    - {name: error_message, type: string, regex_name: errorMessage}
    charset: UTF-8
    newline: LF
    skip_if_unmatch: true
out: {type: mysql, host: localhost, user: dlog, password: '', database: dlog, table: syslog,
  mode: insert}
